import { readFile } from "node:fs/promises";
import type { FeaturedProject, ProfileConfig } from "./projects";

export interface ReadmeRenderInput {
  templatePath: string;
  lastUpdated: string;
  profile: ProfileConfig;
  projects: FeaturedProject[];
  projectCardsSvgPath: string;
}

export async function renderReadme(input: ReadmeRenderInput): Promise<string> {
  const template = await readFile(input.templatePath, "utf8");
  const inProgressProjects = sortedProjects(input.projects, "in_progress");
  const completedProjects = sortedProjects(input.projects, "completed");

  const replacements: Record<string, string> = {
    HERO: renderHero(input.profile),
    IN_PROGRESS_PROJECTS: renderInProgressProjectsTable(inProgressProjects),
    COMPLETED_PROJECTS: renderCompletedProjectsTable(completedProjects),
    TECH_STACK: renderTechStack(input.profile),
    AI_ASSISTED_WORKFLOW: renderAiAssistedWorkflow(input.profile),
    AUTO_GENERATED_INFO: renderAutoGeneratedInfo(input.lastUpdated),
    PROJECT_CARDS_DETAILS: renderOptionalProjectCardsDetails(input.projectCardsSvgPath)
  };

  return Object.entries(replacements).reduce(
    (content, [key, value]) => content.replaceAll(`{{${key}}}`, value),
    template
  );
}

function renderHero(profile: ProfileConfig): string {
  return [
    '<div align="center">',
    "",
    `# ${profile.name}`,
    "",
    `**${profile.role}**`,
    "",
    `${profile.interests.join(" · ")}<br />`,
    "Codex와 GitHub 기반 워크플로우를 활용해<br />",
    "작게 만들고, 검증하고, 반복 개선하는 개발 방식을 연습하고 있습니다.",
    "",
    "</div>"
  ].join("\n");
}

function renderInProgressProjectsTable(projects: FeaturedProject[]): string {
  return renderProjectTable({
    projects,
    columns: ["프로젝트", "설명", "기술", "현재 작업"],
    detailKey: "currentFocus"
  });
}

function renderCompletedProjectsTable(projects: FeaturedProject[]): string {
  return renderProjectTable({
    projects,
    columns: ["프로젝트", "설명", "기술", "구현 결과"],
    detailKey: "result"
  });
}

function renderProjectTable(input: {
  projects: FeaturedProject[];
  columns: [string, string, string, string];
  detailKey: "currentFocus" | "result";
}): string {
  if (input.projects.length === 0) {
    return "표시할 프로젝트가 없습니다.";
  }

  const rows = input.projects.map((project) =>
    [
      renderProjectName(project),
      project.description,
      renderPlainStack(project.stack),
      project[input.detailKey]
    ]
      .map(escapeMarkdownTableCell)
      .join(" | ")
  );

  return [
    `| ${input.columns.join(" | ")} |`,
    "|---|---|---|---|",
    ...rows.map((row) => `| ${row} |`)
  ].join("\n");
}

function renderTechStack(profile: ProfileConfig): string {
  return [
    "| 구분 | 기술 |",
    "|---|---|",
    ...profile.techStackGroups.map((group) => `| ${group.category} | ${group.items.join(", ")} |`)
  ].join("\n");
}

function renderAiAssistedWorkflow(profile: ProfileConfig): string {
  return profile.workflow.map((item) => `- ${item}`).join("\n");
}

function renderAutoGeneratedInfo(lastUpdated: string): string {
  return [`이 README는 TypeScript generator와 GitHub Actions로 생성됩니다.`, `마지막 갱신: ${lastUpdated}`].join(
    "\n"
  );
}

function renderOptionalProjectCardsDetails(projectCardsSvgPath: string): string {
  return [
    "<details>",
    "<summary>자동 생성 프로젝트 카드 보기</summary>",
    "",
    `<img src="${projectCardsSvgPath}" alt="자동 생성 프로젝트 카드" width="100%" />`,
    "",
    "</details>"
  ].join("\n");
}

function sortedProjects(projects: FeaturedProject[], status: FeaturedProject["status"]): FeaturedProject[] {
  return projects.filter((project) => project.status === status).sort((a, b) => a.priority - b.priority);
}

function renderProjectName(project: FeaturedProject): string {
  if (project.isPublic && project.displayUrl) {
    return `[${project.name}](${project.url})`;
  }

  return project.name;
}

function renderPlainStack(stack: string[]): string {
  return stack.join(", ");
}

function escapeMarkdownTableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}
